## Info service to pass info to gui

# action type, that is an enum and with msg we can only define it like this
# remember to add here if we add new type in Action.h and ActionPrimitive.h ..
uint8 ALL = 0
uint8 PRIMITIVE = 1
uint8 GENERIC_and_COMPOSED = 2 
uint8 TIMED = 3

#request 
#if some caller is asking for only a type, otherwise 0 is the default then all action are sent
uint8 actionType
---
ActionInfo[] actionsInfo
